### ISSUE TITLE
Add a thumbnail in settings pane

### ISSUE THREAD

**Issue by tessi** [tessi/LazyNethack#8]
The appereance of the screensaver in the macos settings pane is quite sad at the moment.

<img width="645" alt="screen shot 2018-10-05 at 20 07 27" src="https://user-images.githubusercontent.com/206108/46552232-5d631380-c8da-11e8-9a5f-8208fc201f5f.png">

We may need a screensaver icon and a preview in the settings pane. For the preview it might be enough to remove `if isPreview { return }` in `LazyNethackView.swift` (combined with extensive testing).

**Comment by celinrayen** [comment]
I can Take it. Can you please provide more details?

**Comment by tessi** [comment]
there are proper previews on master now

<img width="670" alt="screen shot 2018-10-06 at 21 12 06" src="https://user-images.githubusercontent.com/206108/46575020-8d2f1b80-c9ad-11e8-9dd7-b103bbeebb27.png">
